version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/test
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: /start_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: /start_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /start_server.sh
      timeout: 300
      runas: root
